### ISSUE TITLE
FileSystemModelSpec should accept model uri with the relative path to the YAML spec

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#218]
For example, a yaml spec like

```yaml
# s3://bucket/to/path/spec.yml
version: 1.0
model:
   uri: models/yolov5.pt
...
```

It should go to `s3://bucket/to/path/models/yolov5.pt` to find the model weights
